version: "3.8"

services:
  web:
    image: websitebanhang_app # Thay bằng tên image thực tế của bạn
    container_name: websitebanhang_container
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_container
    environment:
      SA_PASSWORD: "Thanhdat53140"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
